missing dev dependancies (babel-core, babel-loader)
modrzew/gumtree-scraper pull request #2
Opened 2017-05-10 09:22 UTC by anisjonischkeit

babel-core and babel-loader are missing in the dev dependancies. these are needed to run `./node_modules/webpack/bin/webpack.js -d`

2017-05-22 14:14 UTC, modrzew requested changes
Verified that indeed, `babel-core` was missing. I'll merge it after duplicated `babel-loader` is removed. Good job :+1:

2017-05-22 14:14 UTC, modrzew commented on package.json
> +    "babel-loader": "^6.4.1",
`babel-loader` is already defined in dependencies, no need for it here again.

2017-05-23 00:21 UTC, anisjonischkeit commented
committed and pushed

2017-05-23 16:38 UTC, modrzew approved these changes

2017-05-23 16:38 UTC, merged